import type { TranslationKey } from '../lib/i18n';
import type { ModelConfig } from '../types/app';

export const MODELS: ModelConfig[] = [
  {
    id: 'u2netp',
    name: 'U2Netp',
    resolution: 320,
    size: '~4MB',
    filename: 'u2netp.onnx',
    descKey: 'model.u2netp.desc',
  },
  {
    id: 'u2net',
    name: 'U2Net',
    resolution: 320,
    size: '~168MB',
    filename: 'u2net.onnx',
    descKey: 'model.u2net.desc',
  },
  {
    id: 'u2net_human_seg',
    name: 'U2Net Human Seg',
    resolution: 320,
    size: '~168MB',
    filename: 'u2net_human_seg.onnx',
    descKey: 'model.u2net_human_seg.desc',
  },
  {
    id: 'silueta',
    name: 'Silueta',
    resolution: 320,
    size: '~42MB',
    filename: 'silueta.onnx',
    descKey: 'model.silueta.desc',
  },
  {
    id: 'isnet-general-use',
    name: 'ISNet General',
    resolution: 1024,
    size: '~170MB',
    filename: 'isnet-general-use.onnx',
    descKey: 'model.isnet-general-use.desc',
  },
  {
    id: 'isnet-anime',
    name: 'ISNet Anime',
    resolution: 1024,
    size: '~168MB',
    filename: 'isnet-anime.onnx',
    descKey: 'model.isnet-anime.desc',
  },
  {
    id: 'large',
    name: 'Large (imgly)',
    resolution: 1024,
    size: '~176MB',
    filename: 'large.onnx',
    descKey: 'model.large.desc',
  },
  {
    id: 'medium',
    name: 'Medium (imgly)',
    resolution: 1024,
    size: '~88MB',
    filename: 'medium.onnx',
    descKey: 'model.medium.desc',
  },
  {
    id: 'small',
    name: 'Small (imgly)',
    resolution: 1024,
    size: '~44MB',
    filename: 'small.onnx',
    descKey: 'model.small.desc',
  },
  {
    id: 'PPModnet_MobileNetV2',
    name: 'PPModnet MobileNetV2',
    resolution: 320,
    size: '~26MB',
    filename: 'PPModnet_MobileNetV2.onnx',
    descKey: 'model.PPModnet_MobileNetV2.desc',
  },
];
